#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
TARGET_DATE="${1:-$(TZ=Asia/Seoul date +%F)}"

# 장중 저부하 증분 스냅샷: 핵심 판정축만 미리 갱신해 12:00 점검 시 burst를 낮춘다.
MONITOR_SNAPSHOT_PROFILE="${MONITOR_SNAPSHOT_PROFILE:-intraday_light}" \
MONITOR_SNAPSHOT_IO_DELAY_SEC="${MONITOR_SNAPSHOT_IO_DELAY_SEC:-1.2}" \
MONITOR_SNAPSHOT_START_JITTER_SEC="${MONITOR_SNAPSHOT_START_JITTER_SEC:-30}" \
MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON="${MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON:-1}" \
MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES="${MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES:-5}" \
"$PROJECT_DIR/deploy/run_monitor_snapshot_safe.sh" "$TARGET_DATE"
