#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
TARGET_DATE="${1:-$(TZ=Asia/Seoul date +%F)}"

# BUY drought 중간점검(장중)에서 스토리지 I/O burst 완화를 위한 경량 실행 프로필.
MONITOR_SNAPSHOT_PROFILE="${MONITOR_SNAPSHOT_PROFILE:-intraday_light}" \
MONITOR_SNAPSHOT_IO_DELAY_SEC="${MONITOR_SNAPSHOT_IO_DELAY_SEC:-1.2}" \
MONITOR_SNAPSHOT_START_JITTER_SEC="${MONITOR_SNAPSHOT_START_JITTER_SEC:-45}" \
MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON="${MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON:-1}" \
MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES="${MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES:-5}" \
"$PROJECT_DIR/deploy/run_monitor_snapshot_safe.sh" "$TARGET_DATE"
