#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
TARGET_DATE="${1:-$(TZ=Asia/Seoul date +%F)}"

# noon full 점검은 유지하되 remote 비교/일시 burst를 줄이는 기본값을 적용한다.
MONITOR_SNAPSHOT_PROFILE="${MONITOR_SNAPSHOT_PROFILE:-full}" \
MONITOR_SNAPSHOT_IO_DELAY_SEC="${MONITOR_SNAPSHOT_IO_DELAY_SEC:-1.0}" \
MONITOR_SNAPSHOT_START_JITTER_SEC="${MONITOR_SNAPSHOT_START_JITTER_SEC:-0}" \
MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON="${MONITOR_SNAPSHOT_SKIP_SERVER_COMPARISON:-1}" \
MONITOR_SNAPSHOT_FULL_TREND_MAX_DATES="${MONITOR_SNAPSHOT_FULL_TREND_MAX_DATES:-12}" \
MONITOR_SNAPSHOT_LOCK_WAIT_SEC="${MONITOR_SNAPSHOT_LOCK_WAIT_SEC:-180}" \
MONITOR_SNAPSHOT_NOTIFY_ADMIN="${MONITOR_SNAPSHOT_NOTIFY_ADMIN:-1}" \
"$PROJECT_DIR/deploy/run_monitor_snapshot_safe.sh" "$TARGET_DATE"
